language: cpp

os:
  - osx
  - linux

osx_image: xcode11.3
dist: bionic

addons:
  apt:
    packages:
      - libcpprest-dev
      - qt5-default
      - cmake
      - libboost-all-dev

  homebrew:
    packages:
      - openssl
      - cpprestsdk
      - qt
      - boost
      - cmake

before_script:
  - cd build
  - cmake ..

script:
  - make getit_tests && ./bin/getit_tests
  - make getit