language: cpp

os:
  - osx
  - linux
  
compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
      - libcpprest-dev
      - qt5-default
      - cmake
      - libboost-all-dev

  homebrew:
    update: true
    packages:
      - openssl
      - cpprestsdk
      - qt5
      - boost
      - cmake

before_script:
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "osx"    ]; then cmake ../ -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2t/lib  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then cmake ../                                                             ; fi

script:
  - make getit_tests && ./bin/getit_tests
  - make getit
