language: cpp

os:
  - macos
  - linux

addons:
  apt:
    packages:
      - libcpprest-dev
      - qt5-default
      - cmake
      - libboost-all-dev

  homebrew:
    packages:
      - openssl
      - cpprestsdk
      - qt
      - boost

before_script:
  - cd build
  - cmake ../

script:
  - make getit_tests
  - make getit